
title: linuxposting.xyz
description: >-
  Linux users having fun i guess...
url: "https://linuxposting.xyz"
defaults:
  - scope:
      path: "" 
    values:
      layout: default
      title: "linuxposting.xyz"
      headline: "linuxposting.xyz"

# Build settings
plugins:
  - jekyll-feed

collections_dir: articles
collections:
  news:
    output: true
    permalink: /news/:path
  announce:
    output: true
    permalink: /announcements/:path

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
